export const wordList = {
    "divide into": "把…分成…(divide)",
    "by the time": "到…为止(time)",
    "make sure": "确保(sure)",
    "have a hard time doing sth.": "做某事有困难(time)",
    "prepare for": "为…做准备(prepare)",
    "make great contributions to": "为…做贡献(contribution)",
    "had better (not) do sth.": "最好(不)做某事(better)",
    "avoid doing sth.": "避免做某事(avoid)",
    "be fond of doing sth.": "喜欢做某事(fond)",
    "in person": "亲自(person)",
    "stay awake": "保持清醒(awake)",
    "make room for": "为…腾出空间(room)",
    "give sb. some advice on": "给某人关于…的建议(advice)",
    "go to bed": "上床睡觉(bed)",
    "remember to do sth.": "记得要做某事(remember)",
    "remember doing sth.": "记得做过某事(remember)",
    "would you like to do sth.": "你愿意做某事吗(would)",
    "be so interested in": "对…如此感兴趣(interested)",
    "improve living standards": "提升生活水平(standard)",
    "take pride in": "以…为傲(pride)",
    "be proud of": "以…为傲(proud)",
    "enjoy doing sth.": "喜欢做某事(enjoy)",
    "make comments on": "就…做评价(comment)",
    "self-introduction": "自我介绍(introduction)",
    "take place": "发生(place)",
    "take the place of": "取代(place)",
    "get rid of": "去除，摆脱(rid)",
    "put into action": "付诸行动，把…付诸实践(action)",
    "put into practice": "付诸行动，把…付诸实践(practice)",
    "attract one's attention": "吸引某人的注意力(attract)",
    "draw one's attention": "吸引某人的注意力(draw)",
    "catch one's attention": "吸引某人的注意力(catch)",
    "pay attention to doing sth.": "注意做某事(attention)",
    "tend to do sth.": "往往会做某事(tend)",
    "achieve one's dream": "实现某人的梦想(achieve)",
    "make one's dream come true": "实现某人的梦想(come)",
    "out of": "出自，缺少，脱离(out)",
    "in addition to doing sth.": "除了做某事之外还有(addition)",
    "at all": "根本，究竟(all)",
    "a lack of": "缺乏(lack->n.)",
    "lacking in": "缺乏(lack->adj.)",
    "be caught in the rain": "淋雨(catch)",
    "much to one's surprise": "令某人非常惊讶的是(much)",
    "different kinds of": "不同种类的(kind)",
    "sing high praise for": "高度赞扬(praise)",
    "play an important role in": "在…中扮演重要角色(role)",
    "play an important part in": "在…方面起重要作用(part)",
    "devote oneself to doing sth.": "投身于做某事(devote)",
    "sb. be devoted to doing sth.": "某人投身于做某事(devoted)",
    "devotion to doing sth.": "对做某事的奉献(devotion)",
    "manage to do sth.": "设法做某事(manage)",
    "a variety of": "各种各样的(variety)",
    "be likely to do sth.": "很可能会做某事(likely to)",
    "it is likely that": "很可能…(likely that)",
    "whether or": "是…还是…(whether)",
    "blow away": "吹走，深深打动(blow)",
    "bring down": "降低，打倒(bring)",
    "keep in touch with": "与…保持联系(touch)",
    "one day": "总有一天(day)",
    "by all means": "当然，无论如何，用一切手段(all)",
    "by any means": "通过任何方式，无论如何(any)",
    "by no means": "决不，绝不(no)",
    "by means of": "通过/依靠…(方法)(means)",
    "be to blame for": "应受谴责，应负责任(blame)",
    "blame sb. for sth.": "因某事责怪某人(blame)",
    "blame sth. on sb.": "把某事怪到某人头上(blame)",
    "be different from": "与…不同(different)",
    "the same as": "与…相同(same)",
    "be similar to": "与…相似(similar)",
    "try one's best": "尽某人最大努力(try)",
    "make the best of": "尽力而为，充分利用(make)",
    "all the best": "万事如意，一切顺利(all)",
    "on condition that": "条件是(condition)"
};